# Generated by Django 2.1.2 on 2019-02-27 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190227_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
